#ifndef GAME_CONFIGURATION_H
#define GAME_CONFIGURATION_H

#define USE_FLAT_STACK 0
#define USE_EN_PASSANT 0
#define USE_UNSORTED_STACK 0
#define ONLY_GENERATE_LEGAL_MOVES 0
#define DONT_USE_ITERATIVE_DEEPENING 0
#define DONT_USE_EVALUATION_CACHING 0
#define DONT_USE_TIME_CONSTRAINT 0

#define DEFAULT_PLY 5
#define MAX_SEARCH_TIME 30000	//max milliseconds per turn

#endif